export const DATASET_VERSION = "clinc150-full-v1";

export const DOMAINS = [
  "banking",
  "credit_cards",
  "kitchen_dining",
  "home",
  "auto_commute",
  "travel",
  "utility",
  "work",
  "small_talk",
  "meta",
] as const;

export type Domain = (typeof DOMAINS)[number];

export const DOMAIN_LABELS: Record<Domain, string> = {
  banking: "Banking",
  credit_cards: "Credit cards",
  kitchen_dining: "Kitchen & dining",
  home: "Home",
  auto_commute: "Auto & commute",
  travel: "Travel",
  utility: "Utility",
  work: "Work",
  small_talk: "Small talk",
  meta: "Meta",
};

/**
 * 10-domain map for CLINC150. Banking / credit cards / travel / work follow
 * Salesforce DNNC's paper-derived map. The remaining six domains follow the
 * standard 15-intent-per-domain organization from Larson et al. Domain is
 * secondary UI/analysis metadata only — scoring uses exact intent labels.
 */
export const DOMAIN_INTENTS: Record<Domain, readonly string[]> = {
  banking: [
    "transfer",
    "transactions",
    "balance",
    "freeze_account",
    "pay_bill",
    "bill_balance",
    "bill_due",
    "interest_rate",
    "routing",
    "min_payment",
    "order_checks",
    "pin_change",
    "report_fraud",
    "account_blocked",
    "spending_history",
  ],
  credit_cards: [
    "credit_score",
    "report_lost_card",
    "credit_limit",
    "rewards_balance",
    "new_card",
    "application_status",
    "card_declined",
    "international_fees",
    "apr",
    "redeem_rewards",
    "credit_limit_change",
    "damaged_card",
    "replacement_card_duration",
    "improve_credit_score",
    "expiration_date",
  ],
  kitchen_dining: [
    "accept_reservations",
    "cancel_reservation",
    "confirm_reservation",
    "cook_time",
    "calories",
    "food_last",
    "how_busy",
    "ingredient_substitution",
    "ingredients_list",
    "meal_suggestion",
    "nutrition_info",
    "recipe",
    "restaurant_reservation",
    "restaurant_reviews",
    "restaurant_suggestion",
  ],
  home: [
    "calendar",
    "calendar_update",
    "next_song",
    "order",
    "order_status",
    "play_music",
    "reminder",
    "reminder_update",
    "shopping_list",
    "shopping_list_update",
    "smart_home",
    "todo_list",
    "todo_list_update",
    "update_playlist",
    "what_song",
  ],
  auto_commute: [
    "current_location",
    "directions",
    "distance",
    "gas",
    "gas_type",
    "jump_start",
    "last_maintenance",
    "mpg",
    "oil_change_how",
    "oil_change_when",
    "schedule_maintenance",
    "tire_change",
    "tire_pressure",
    "traffic",
    "uber",
  ],
  travel: [
    "book_flight",
    "book_hotel",
    "car_rental",
    "travel_suggestion",
    "travel_alert",
    "travel_notification",
    "carry_on",
    "timezone",
    "vaccines",
    "translate",
    "flight_status",
    "international_visa",
    "lost_luggage",
    "plug_type",
    "exchange_rate",
  ],
  utility: [
    "alarm",
    "calculator",
    "date",
    "definition",
    "find_phone",
    "flip_coin",
    "make_call",
    "measurement_conversion",
    "roll_dice",
    "share_location",
    "spelling",
    "text",
    "time",
    "timer",
    "weather",
  ],
  work: [
    "direct_deposit",
    "pto_request",
    "taxes",
    "payday",
    "w2",
    "pto_balance",
    "pto_request_status",
    "next_holiday",
    "insurance",
    "insurance_change",
    "schedule_meeting",
    "pto_used",
    "meeting_schedule",
    "rollover_401k",
    "income",
  ],
  small_talk: [
    "are_you_a_bot",
    "do_you_have_pets",
    "fun_fact",
    "goodbye",
    "greeting",
    "how_old_are_you",
    "meaning_of_life",
    "tell_joke",
    "thank_you",
    "what_are_your_hobbies",
    "what_can_i_ask_you",
    "what_is_your_name",
    "where_are_you_from",
    "who_do_you_work_for",
    "who_made_you",
  ],
  meta: [
    "cancel",
    "change_accent",
    "change_ai_name",
    "change_language",
    "change_speed",
    "change_user_name",
    "change_volume",
    "maybe",
    "no",
    "repeat",
    "reset_settings",
    "sync_device",
    "user_name",
    "whisper_mode",
    "yes",
  ],
};

export const INTENT_DESCRIPTIONS: Record<string, string> = {
  transfer: "Move money between the user's own bank accounts.",
  transactions: "List recent bank transactions or account activity.",
  balance: "Check the current bank account balance.",
  freeze_account: "Freeze or lock a bank account.",
  pay_bill: "Pay a bill from a bank account.",
  bill_balance: "Ask how much is owed on a bill.",
  bill_due: "Ask when a bill is due.",
  interest_rate: "Ask about a bank or savings interest rate.",
  routing: "Ask for a bank routing number.",
  min_payment: "Ask the minimum payment due.",
  order_checks: "Order new paper checks.",
  pin_change: "Change a bank or debit card PIN.",
  report_fraud: "Report fraudulent bank activity.",
  account_blocked: "Ask why a bank account is blocked or restricted.",
  spending_history: "Review spending history or category spend.",
  credit_score: "Check the user's credit score.",
  report_lost_card: "Report a lost or stolen credit card.",
  credit_limit: "Ask the current credit card limit.",
  rewards_balance: "Check credit card rewards or points balance.",
  new_card: "Request or activate a new credit card.",
  application_status: "Check status of a credit card application.",
  card_declined: "Ask why a card payment was declined.",
  international_fees: "Ask about foreign transaction or international fees.",
  apr: "Ask about a card APR or interest rate.",
  redeem_rewards: "Redeem credit card rewards or points.",
  credit_limit_change: "Request a credit limit increase or change.",
  damaged_card: "Replace a damaged credit or debit card.",
  replacement_card_duration: "Ask how long a replacement card will take to arrive.",
  improve_credit_score: "Ask how to improve a credit score.",
  expiration_date: "Ask when a card expires.",
  accept_reservations: "Ask whether a restaurant accepts reservations.",
  cancel_reservation: "Cancel a restaurant reservation.",
  confirm_reservation: "Confirm an existing restaurant reservation.",
  cook_time: "Ask how long a dish takes to cook.",
  calories: "Ask calorie information for food.",
  food_last: "Ask how long leftover food will last.",
  how_busy: "Ask how busy a restaurant is.",
  ingredient_substitution: "Ask for a substitute ingredient.",
  ingredients_list: "Ask for the ingredients in a recipe or dish.",
  meal_suggestion: "Ask for a meal idea or what to cook.",
  nutrition_info: "Ask for nutrition facts beyond calories.",
  recipe: "Ask for a recipe.",
  restaurant_reservation: "Make a restaurant reservation.",
  restaurant_reviews: "Ask for restaurant reviews.",
  restaurant_suggestion: "Ask for a restaurant recommendation.",
  calendar: "Ask what is on the calendar.",
  calendar_update: "Add or change a calendar event.",
  next_song: "Skip to the next song.",
  order: "Place an order for a product.",
  order_status: "Check the status of an existing order.",
  play_music: "Play music.",
  reminder: "Ask about an existing reminder.",
  reminder_update: "Create or change a reminder.",
  shopping_list: "Read the shopping list.",
  shopping_list_update: "Add or remove shopping list items.",
  smart_home: "Control smart home devices.",
  todo_list: "Read the to-do list.",
  todo_list_update: "Add or change to-do list items.",
  update_playlist: "Add or change songs on a playlist.",
  what_song: "Identify the currently playing song.",
  current_location: "Ask the user's current location.",
  directions: "Get driving or transit directions.",
  distance: "Ask the distance to a place.",
  gas: "Find nearby gas stations or gas prices.",
  gas_type: "Ask what type of gas a car uses.",
  jump_start: "Ask how to jump-start a car.",
  last_maintenance: "Ask when the car was last serviced.",
  mpg: "Ask the car's fuel economy / MPG.",
  oil_change_how: "Ask how to change the oil.",
  oil_change_when: "Ask when an oil change is due.",
  schedule_maintenance: "Schedule car maintenance.",
  tire_change: "Ask about changing or replacing tires.",
  tire_pressure: "Ask about tire pressure.",
  traffic: "Ask about current traffic conditions.",
  uber: "Book a rideshare such as Uber.",
  book_flight: "Book a flight.",
  book_hotel: "Book a hotel.",
  car_rental: "Rent a car.",
  travel_suggestion: "Ask for travel destination ideas.",
  travel_alert: "Ask about travel warnings or alerts.",
  travel_notification: "Set a travel notification with a bank or airline.",
  carry_on: "Ask about carry-on baggage rules.",
  timezone: "Ask the time zone of a place.",
  vaccines: "Ask about travel vaccines.",
  translate: "Translate a word or phrase.",
  flight_status: "Check whether a flight is on time.",
  international_visa: "Ask about visa requirements.",
  lost_luggage: "Report or track lost luggage.",
  plug_type: "Ask what electrical plug a country uses.",
  exchange_rate: "Ask a currency exchange rate.",
  alarm: "Set, change, or ask about an alarm.",
  calculator: "Perform a calculation.",
  date: "Ask today's date.",
  definition: "Ask the definition of a word.",
  find_phone: "Find a lost phone.",
  flip_coin: "Flip a coin.",
  make_call: "Place a phone call.",
  measurement_conversion: "Convert units of measurement.",
  roll_dice: "Roll dice.",
  share_location: "Share the user's location.",
  spelling: "Ask how to spell a word.",
  text: "Send a text message.",
  time: "Ask the current time.",
  timer: "Set or check a timer.",
  weather: "Ask about the weather.",
  direct_deposit: "Ask about or set up direct deposit.",
  pto_request: "Request paid time off.",
  taxes: "Ask a question about taxes.",
  payday: "Ask when payday is.",
  w2: "Ask about a W-2 form.",
  pto_balance: "Ask remaining PTO balance.",
  pto_request_status: "Check the status of a PTO request.",
  next_holiday: "Ask when the next holiday is.",
  insurance: "Ask about employee insurance coverage.",
  insurance_change: "Change insurance coverage.",
  schedule_meeting: "Schedule a work meeting.",
  pto_used: "Ask how much PTO has been used.",
  meeting_schedule: "Ask what meetings are scheduled.",
  rollover_401k: "Ask about rolling over a 401k.",
  income: "Ask about income or salary.",
  are_you_a_bot: "Ask whether the assistant is a bot.",
  do_you_have_pets: "Ask whether the assistant has pets.",
  fun_fact: "Ask for a fun fact.",
  goodbye: "End the conversation.",
  greeting: "Say hello or greet the assistant.",
  how_old_are_you: "Ask the assistant's age.",
  meaning_of_life: "Ask about the meaning of life.",
  tell_joke: "Ask the assistant to tell a joke.",
  thank_you: "Thank the assistant.",
  what_are_your_hobbies: "Ask about the assistant's hobbies.",
  what_can_i_ask_you: "Ask what the assistant can do.",
  what_is_your_name: "Ask the assistant's name.",
  where_are_you_from: "Ask where the assistant is from.",
  who_do_you_work_for: "Ask who the assistant works for.",
  who_made_you: "Ask who created the assistant.",
  cancel: "Cancel the current action or request.",
  change_accent: "Change the assistant's speaking accent.",
  change_ai_name: "Rename the assistant.",
  change_language: "Change the assistant's language.",
  change_speed: "Change how fast the assistant speaks.",
  change_user_name: "Change the name the assistant uses for the user.",
  change_volume: "Change the assistant's volume.",
  maybe: "Give an uncertain or maybe response.",
  no: "Answer no or decline.",
  repeat: "Ask the assistant to repeat itself.",
  reset_settings: "Reset assistant settings to defaults.",
  sync_device: "Sync or connect a device.",
  user_name: "Ask what name the assistant has for the user.",
  whisper_mode: "Turn whisper or quiet mode on or off.",
  yes: "Answer yes or confirm.",
};

export type IntentMeta = {
  id: string;
  label: string;
  domain: Domain;
  description: string;
};

function humanize(id: string): string {
  return id.replaceAll("_", " ");
}

export const INTENT_CATALOG: IntentMeta[] = DOMAINS.flatMap((domain) =>
  DOMAIN_INTENTS[domain].map((id) => ({
    id,
    label: humanize(id),
    domain,
    description: INTENT_DESCRIPTIONS[id] ?? humanize(id),
  })),
);

export const CANONICAL_INTENTS = INTENT_CATALOG.map((intent) => intent.id);

export const INTENT_BY_ID = new Map(INTENT_CATALOG.map((intent) => [intent.id, intent]));

export function domainForIntent(intent: string): Domain | "oos" | "unknown" {
  if (intent === "oos") return "oos";
  return INTENT_BY_ID.get(intent)?.domain ?? "unknown";
}

export function intentLabel(intent: string): string {
  if (intent === "oos") return "out of scope";
  return INTENT_BY_ID.get(intent)?.label ?? humanize(intent);
}

export function domainLabel(domain: string): string {
  if (domain === "oos") return "Out of scope";
  return DOMAIN_LABELS[domain as Domain] ?? domain;
}

export function choiceCriteria(): Record<string, string> {
  return Object.fromEntries(INTENT_CATALOG.map((intent) => [intent.id, intent.description]));
}
